### PR TITLE
supports different dimension

### PR DESCRIPTION
**Pull request by JamesChuanggg**
Hi, I modified some codes in ```CompactBilinearPooling.lua``` to make it support different dimension of two input vectors. Please check it!

### CODE REVIEW

**Comment by jnhwkim** [comment]
@JamesChuanggg Thanks! 
However, this code is maintained using test cases. Can you update `cbptest.testPsi()` in `test/test.lua` resulting an error. This test case checks the expectation of psi functions.

**Comment by JamesChuanggg** [comment]
Thanks for reply. I'm wondering why using "dot" to measure the error since we can not computer dot for two vector with different length.

**Comment by jnhwkim** [comment]
@JamesChuanggg You're right. It's for the compatibility check. Multimodal version is extended from unimodal version. In Section 3.2 of Gao et al. (2015), there is a property of E[<Ψ(x, h, s),Ψ(y,h, s)>] =
<x, y> about the phi(Ψ) function. The test case makes sure this property. 

Could you update the test case having the same-sized vectors to check the phi function as before?

**Comment by JamesChuanggg** [comment]
I've modified function psi() in ```CompactBilinearPooling.lua``` to make it support same homogeneous case and ```test/test.lua`` return no error.

**Comment by jnhwkim** [comment]
@JamesChuanggg Thanks!

**Pull request merged**
